export const BUS_STOPS: string[] = [
  '1 Apriliou - Georgiou Griva Digeni',
  '1 Apriliou - Papamiichail Konstantinou',
  '1 Maiou - 7th Kornos',
  '1 Maiou - 8th Kornos',
  '1st Stop Maroni',
  '1st Stop Melini',
  '1st Stop Psematismenos',
  '1st Stop Tochni',
  '2nd Stop Maroni',
  '2nd Stop Psematismenos',
  '2nd Stop Tochni',
  '2nd Stop Vavatsinia',
  '2nd Stop Vavla',
  '3rd Stop Tochni',
  '3rd Stop Vavatsinia',
  '4th Stop Tochni',
  '4th Stop Vavatsinia',
  '5th Stop Tochni',
  '6th Stop Tochni',
  '7th Stop Tochni',
  '8th Stop Tochni',
  '9th Stop Tochni',
  '10th Stop Tochni',
  '11th Stop Tochni',
  'Ag. Anna Comm. Board',
  'Ag. Dimitrios Church',
  'Ag. Epifanios Church',
  'Ag. Fanouriou - 3rd Stop',
  'Ag. Fanouriou - 4th Stop',
  'Ag. Fanouriou - 7th Stop',
  'Ag. Fanouriou - 8th Stop',
  'Ag. Ioannis Church',
  'Ag. Kon/nou kai Elenis',
  'Ag. Louka Ave. - Dipotamou',
  'Ag. Marina Church',
  'Ag. Paraskevis - 1st Stop',
  'Ag. Paraskevis - 2nd Stop',
  'Ag. Vavatsinias - Ora Road - 1st Stop',
  'Ag. Vavatsinias - Ora Road - 2nd Stop',
  'Ancient Idalion Museum',
  'Anexartisias - 1st Kornos',
  'Anexartisias - 2nd Kornos',
  'Anexartisias - Stadiou',
  'Antonaki Manoli - 10th Stop',
  'Apodimon Square',
  'Archiep. Makariou C - Diogenous',
  'Archiep. Makariou C - Elpidos',
  "Archiep. Makariou C' - Omirou",
  "Archiep. Makariou C' Ave. - 1st Stop",
  "Archiep. Makariou C' Ave. - 2nd Stop",
  "Archiep. Makariou C' Ave. - 3rd Stop",
  "Archiep. Makariou C' Ave. - 4th Stop",
  "Archiep. Makariou C' Ave. - 5th Stop",
  "Archiep. Makariou C' Ave. - 6th Stop",
  "Archiep. Makariou C' Ave. - Grigori Afxentiou",
  'Artemidos Ave. - Faneromenis Ave.',
  'Artemidos Ave. - Okkoular',
  'Artemidos Ave. - Patticheion',
  'Artemidos Ave. - Salt Lake',
  'Artemidos Ave. - Tasou Mitsopoulou Ave.',
  'Artemidos Ave. - Touzchane',
  'Ave. Lemesou - Arch. Makariou C',
  'Ave. Lemesou - Kimonos',
  'Ave. Lemesou - Larnakos',
  'Ayia Napa',
  'Chalkanoros',
  'Chalkanoros - Post Office',
  'Choirokoitia - Vavla Road - 1st Stop',
  'Choirokoitia - Vavla Road - 2nd Stop',
  'Choirokoitia - Vavla Road - 3rd Stop',
  'Choirokoitia Comm. Stadium',
  'Choirokoitia Elem. School',
  'Choirokoitia Neolithic Settlement',
  'Choirokoitia Village Centre',
  'Chrysosotiros Church - Eirinis Avenue',
  'Coral Bay',
  'Dali Health Centre',
  'Delikipos',
  'Distrato Lefkara - Kato Drys',
  'Egkomis - Palaikythrou',
  "Elem. School B' Nisou",
  'Eleftheriou Venizelou - Ifaistou',
  'Famagusta / Ammochostos',
  'Grigori Afxentiou - 3rd Kornos',
  'Grigori Afxentiou - 4th Kornos',
  'Grigori Afxentiou - 5th Kornos',
  'Grigori Afxentiou Ave. - Apost. Andreou',
  'Grigori Afxentiou Ave. - Apost. Louka',
  'Grigori Afxentiou Ave. - Stadiou',
  'Griva Digeni - 10th Stop',
  'Isaak kai Solomou - Petraki Giallourou',
  'Kalo Chorio Cemetery',
  'Kato Dris Rural Museum',
  'Kofinou - Highway Exit',
  'Kofinou Police Station',
  'Kofinou Station',
  'Kornos - Delikipos Road',
  'Larnaca',
  'Larnaca Airport',
  'Larnaka',
  'Larnaka Airport',
  'Larnaka Courthouse',
  'Larnaka Municipal Theatre',
  'Larnakos - 1st Pyrga Larnakas',
  'Larnakos Ave. - Ap. Varnava',
  'Latchi',
  'Lefkara - Vavatsinia Road - 1st Stop',
  'Lefkara - Vavatsinia Road - 2nd Stop',
  'Lefkosia - Lemesos Old Road - 1st Stop',
  'Lefkosia - Lemesos Old Road - 2nd Stop',
  'Lefkosias Ave. - Ammochostou',
  'Lefkosias Ave. - Artemidos',
  'Lefkosias Ave. - Grigori Afxentiou',
  'Limassol / Lemesos',
  'Lympia Comm. Board',
  "Makariou C' Ave. - Larnakos Ave.",
  'Maroni Elem. School',
  'Mosfiloti Cemetery',
  'Mosfiloti Elem. School',
  'Nicosia / Lefkosia',
  'Nissi Beach',
  'Old Hospital',
  'Pafos',
  'Pafos Airport',
  'Panagias Eleousas Ave.',
  'Paphos',
  'Paphos Airport',
  'Paralimni',
  'Pera Chorio Nisou High School',
  'Platini Museum',
  'Polis Chrysochous',
  'Protaras',
  'Psevdas Comm. Stadium',
  'Psevdas Square',
  'Pyrga - Kornos Road',
  'Pyrga Larnaka Elem. School',
  'Saint Raphael Hospital',
  'Theodorou Mavrosavva - Athinas',
  'Timios Prodromos Church',
  'Troodos',
];

// Major route connections between key cities
export type Route = {
  from: string;
  to: string;
  duration: string;
  changes: number;
  departures: string[];
  operator: string;
  price: string;
};

const ROUTES: { [key: string]: Route[] } = {
  'nicosia-larnaca': [
    { from: 'Nicosia / Lefkosia', to: 'Larnaca', duration: '45 min', changes: 0, departures: ['07:00', '08:30', '10:00', '12:00', '14:00', '16:00', '18:00'], operator: 'OSEA', price: '€3.00' },
  ],
  'nicosia-limassol': [
    { from: 'Nicosia / Lefkosia', to: 'Limassol / Lemesos', duration: '1 Std 15 min', changes: 0, departures: ['07:30', '09:00', '11:00', '13:00', '15:30', '17:30'], operator: 'EMEL', price: '€4.00' },
  ],
  'nicosia-paphos': [
    { from: 'Nicosia / Lefkosia', to: 'Paphos', duration: '2 Std', changes: 1, departures: ['08:00', '12:00', '16:00'], operator: 'EMEL / OSEA', price: '€6.00' },
  ],
  'larnaca-ayia-napa': [
    { from: 'Larnaca', to: 'Ayia Napa', duration: '1 Std', changes: 0, departures: ['08:00', '10:00', '12:00', '14:00', '16:00', '18:00'], operator: 'OSEA', price: '€3.50' },
  ],
  'larnaca-limassol': [
    { from: 'Larnaca', to: 'Limassol / Lemesos', duration: '1 Std 30 min', changes: 0, departures: ['07:00', '09:30', '12:00', '14:30', '17:00'], operator: 'EMEL', price: '€4.00' },
  ],
  'limassol-paphos': [
    { from: 'Limassol / Lemesos', to: 'Paphos', duration: '1 Std 15 min', changes: 0, departures: ['07:00', '09:00', '11:00', '13:00', '15:00', '17:00', '19:00'], operator: 'OSEA', price: '€3.50' },
  ],
  'larnaca-nicosia': [
    { from: 'Larnaca', to: 'Nicosia / Lefkosia', duration: '45 min', changes: 0, departures: ['06:30', '08:00', '10:00', '12:00', '14:00', '16:00', '18:00'], operator: 'OSEA', price: '€3.00' },
  ],
  'limassol-nicosia': [
    { from: 'Limassol / Lemesos', to: 'Nicosia / Lefkosia', duration: '1 Std 15 min', changes: 0, departures: ['07:00', '09:00', '11:00', '13:00', '15:00', '17:00'], operator: 'EMEL', price: '€4.00' },
  ],
  'paphos-limassol': [
    { from: 'Paphos', to: 'Limassol / Lemesos', duration: '1 Std 15 min', changes: 0, departures: ['06:30', '08:30', '10:30', '12:30', '14:30', '16:30', '18:30'], operator: 'OSEA', price: '€3.50' },
  ],
  'ayia-napa-larnaca': [
    { from: 'Ayia Napa', to: 'Larnaca', duration: '1 Std', changes: 0, departures: ['07:00', '09:00', '11:00', '13:00', '15:00', '17:00'], operator: 'OSEA', price: '€3.50' },
  ],
};

export function findRoute(from: string, to: string): Route | null {
  const normalize = (s: string) => s.toLowerCase().replace(/\s*\/\s*/g, '-').replace(/\s+/g, '-').replace(/[^a-z-]/g, '');

  for (const key of Object.keys(ROUTES)) {
    if (key.includes(normalize(from).split('-')[0]) && key.includes(normalize(to).split('-')[0])) {
      const routes = ROUTES[key];
      if (routes && routes.length > 0) return routes[0];
    }
  }
  return null;
}
